-- MySQL Script generated by MySQL Workbench
-- Mon Jul  1 21:28:34 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema proyectomoviles
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema proyectomoviles
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `proyectomoviles` ;
USE `proyectomoviles` ;

-- -----------------------------------------------------
-- Table `proyectomoviles`.`tipo_tarj_metro`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `proyectomoviles`.`tipo_tarj_metro` (
  `tipo_tarj_id` INT NOT NULL AUTO_INCREMENT,
  `tipo_tarj_descripcion` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`tipo_tarj_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `proyectomoviles`.`tarjeta_metro`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `proyectomoviles`.`tarjeta_metro` (
  `tarj_id` INT NOT NULL AUTO_INCREMENT,
  `tarj_saldo` DECIMAL(3,2) NOT NULL,
  `tipo_tarj_id` INT NOT NULL,
  PRIMARY KEY (`tarj_id`, `tipo_tarj_id`),
  INDEX `fk_tarjeta_metro_tipo_tarj_metro1_idx` (`tipo_tarj_id` ASC) VISIBLE,
  CONSTRAINT `fk_tarjeta_metro_tipo_tarj_metro1`
    FOREIGN KEY (`tipo_tarj_id`)
    REFERENCES `proyectomoviles`.`tipo_tarj_metro` (`tipo_tarj_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `proyectomoviles`.`pago_debito`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `proyectomoviles`.`pago_debito` (
  `debito_id` INT NOT NULL AUTO_INCREMENT,
  `debito_num_tarjeta` INT NOT NULL,
  `debito_fecha_caducidad` DATETIME NOT NULL,
  `debito_ccv` INT NOT NULL,
  PRIMARY KEY (`debito_id`))
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `proyectomoviles`.`recargas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `proyectomoviles`.`recargas` (
  `tarjeta_metro_id` INT NOT NULL,
  `tarjeta_metro_tipo_id` INT NOT NULL,
  `pago_debito_id` INT NOT NULL,
  `recargas_fecha` DATETIME NOT NULL,
  `recarga_monto` DECIMAL(3,2) NOT NULL,
  `observaciones` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`tarjeta_metro_id`, `tarjeta_metro_tipo_id`, `pago_debito_id`),
  INDEX `fk_tarjeta_metro_has_pago_debito_pago_debito1_idx` (`pago_debito_id` ASC) VISIBLE,
  INDEX `fk_tarjeta_metro_has_pago_debito_tarjeta_metro1_idx` (`tarjeta_metro_id` ASC, `tarjeta_metro_tipo_id` ASC) VISIBLE,
  CONSTRAINT `fk_tarjeta_metro_has_pago_debito_tarjeta_metro1`
    FOREIGN KEY (`tarjeta_metro_id` , `tarjeta_metro_tipo_id`)
    REFERENCES `proyectomoviles`.`tarjeta_metro` (`tarj_id` , `tipo_tarj_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tarjeta_metro_has_pago_debito_pago_debito1`
    FOREIGN KEY (`pago_debito_id`)
    REFERENCES `proyectomoviles`.`pago_debito` (`debito_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `proyectomoviles`.`cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `proyectomoviles`.`cliente` (
  `cli_id` INT NOT NULL AUTO_INCREMENT,
  `cli_nombre` VARCHAR(45) NOT NULL,
  `cli_apellido` VARCHAR(45) NOT NULL,
  `cli_correo` VARCHAR(45) NOT NULL,
  `cli_contraseña` VARCHAR(45) NULL,
  `fk_tarj_id` INT NOT NULL,
  PRIMARY KEY (`cli_id`, `fk_tarj_id`),
  INDEX `fk_cliente_tarjeta_metro_idx` (`fk_tarj_id` ASC) VISIBLE,
  CONSTRAINT `fk_cliente_tarjeta_metro`
    FOREIGN KEY (`fk_tarj_id`)
    REFERENCES `proyectomoviles`.`tarjeta_metro` (`tarj_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;



SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

